In [3]:
import torch
t = torch.tensor([[3,2],[4,5],[1,7]])

In [4]:
t.size() == (3, 2)

True

In [10]:
 "%s"   %(str((5,3,9)))

'(5, 3, 9)'

In [12]:
str(t.size())

'torch.Size([3, 2])'

In [15]:
t.size().item

AttributeError: 'torch.Size' object has no attribute 'item'

torch.Size([3, 2, 3])

In [32]:
dist = torch.tensor([0.1, 0.2, 0.2, 0.5])

In [33]:
torch.multinomial(dist, 10, replacement= True)

tensor([1, 3, 2, 1, 1, 3, 3, 3, 2, 3])

In [24]:
dist

tensor([0.5000, 0.2000, 0.3000])

In [52]:
b = torch.tensor( [[.05, .9, .05], [.1, .8, .1]])

In [53]:
torch.multinomial(b, 1, replacement=True)

tensor([[1],
        [1]])

In [55]:
batch_size = 32
seq_len = 20
vocab_size = 8
testing_tensor =torch.randn(batch_size,seq_len, vocab_size )

In [74]:
testing_tensor.size()

torch.Size([32, 20, 8])

In [63]:
lengths = torch.randint(1, 21, (batch_size, 1)).squeeze(1)

In [67]:
final_index = lengths - 1

In [66]:
import torch.nn.functional as F

In [76]:
F.one_hot(F.one_hot(final_index, seq_len))

tensor([[[1, 0],
         [1, 0],
         [1, 0],
         ...,
         [1, 0],
         [1, 0],
         [1, 0]],

        [[1, 0],
         [1, 0],
         [1, 0],
         ...,
         [1, 0],
         [1, 0],
         [1, 0]],

        [[1, 0],
         [1, 0],
         [1, 0],
         ...,
         [1, 0],
         [1, 0],
         [1, 0]],

        ...,

        [[1, 0],
         [1, 0],
         [1, 0],
         ...,
         [1, 0],
         [1, 0],
         [1, 0]],

        [[1, 0],
         [0, 1],
         [1, 0],
         ...,
         [1, 0],
         [1, 0],
         [1, 0]],

        [[1, 0],
         [1, 0],
         [1, 0],
         ...,
         [1, 0],
         [1, 0],
         [1, 0]]])

In [71]:
final_index.size()

torch.Size([32])

In [90]:
bs = testing_tensor[torch.arange(testing_tensor.size(0)),final_index,:]

In [92]:
out = F.softmax(bs, dim= -1)

In [94]:
out[0].sum()

tensor(1.0000)

In [98]:
torch.multinomial(out, num_samples= 1).size()

torch.Size([32, 1])

In [103]:
torch.argmax(out, dim = -1).size()

torch.Size([32])

In [101]:
out.size()

torch.Size([32, 8])

In [1]:
from Controller.TrainingController import TrainingController

/Users/jrhs/.pyenv/versions/dl/lib/python3.9/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [2]:
trainer = TrainingController()

| Preprocessed data loaded successfully |
/Users/jrhs/.pyenv/versions/dl/lib/python3.9/site-packages/torch/nn/modules/rnn.py:60: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "


<Figure size 1600x800 with 0 Axes>

In [3]:
caseids, data, target, lengths  = iter(trainer.train_data_loader).next()

In [4]:
predicted, hidden_state  = trainer.model.predict_next(input=data, lengths= lengths, use_argmax= False)

In [5]:
predicted_list = trainer.model.predict_next_n(input= data, lengths= lengths, use_argmax= True, n= 5)

In [6]:
from Utils.Constants import Constants

In [7]:
predicted_list[5]

[2,
 12,
 9,
 10,
 27,
 28,
 3,
 17,
 8,
 15,
 19,
 33,
 26,
 34,
 32,
 34,
 32,
 34,
 17,
 14,
 15,
 19,
 33,
 32,
 34,
 32,
 34,
 18,
 36,
 32,
 37,
 13,
 4,
 5,
 11,
 35,
 5,
 24,
 10,
 12,
 7]

In [8]:
trainer.dataset.list_of_index_to_vocab(predicted_list[5])

['<SOS>',
 'A_SUBMITTED_COMPLETE',
 'A_PARTLYSUBMITTED_COMPLETE',
 'A_PREACCEPTED_COMPLETE',
 'W_Completeren aanvraag_SCHEDULE',
 'W_Completeren aanvraag_START',
 'A_ACCEPTED_COMPLETE',
 'O_SELECTED_COMPLETE',
 'A_FINALIZED_COMPLETE',
 'O_CREATED_COMPLETE',
 'O_SENT_COMPLETE',
 'W_Nabellen offertes_SCHEDULE',
 'W_Completeren aanvraag_COMPLETE',
 'W_Nabellen offertes_START',
 'W_Nabellen offertes_COMPLETE',
 'W_Nabellen offertes_START',
 'W_Nabellen offertes_COMPLETE',
 'W_Nabellen offertes_START',
 'O_SELECTED_COMPLETE',
 'O_CANCELLED_COMPLETE',
 'O_CREATED_COMPLETE',
 'O_SENT_COMPLETE',
 'W_Nabellen offertes_SCHEDULE',
 'W_Nabellen offertes_COMPLETE',
 'W_Nabellen offertes_START',
 'W_Nabellen offertes_COMPLETE',
 'W_Nabellen offertes_START',
 'O_SENT_BACK_COMPLETE',
 'W_Valideren aanvraag_SCHEDULE',
 'W_Nabellen offertes_COMPLETE',
 'W_Valideren aanvraag_START',
 'O_ACCEPTED_COMPLETE',
 'A_ACTIVATED_COMPLETE',
 'A_APPROVED_COMPLETE',
 'A_REGISTERED_COMPLETE',
 'W_Valideren aanvraag_C

In [19]:
trainer.dataset.vocab_to_index(Constants.EOS_VOCAB)

1

In [26]:
a = [3,4,5,6,7,8]

In [30]:
a[: 200]

[3, 4, 5, 6, 7, 8]

In [31]:
a[:-1]

[3, 4, 5, 6, 7]

In [ ]:
len

In [8]:
vacab = [trainer.dataset.list_of_index_to_vocab(pl) for  pl  in predicted_list]

In [10]:
[len(i)for i in vacab]

[61,
 54,
 49,
 43,
 41,
 37,
 36,
 35,
 34,
 33,
 30,
 28,
 25,
 25,
 25,
 23,
 18,
 17,
 17,
 15,
 14,
 13,
 13,
 13,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10]

[[2,
  12,
  9,
  10,
  27,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  3,
  8,
  17,
  15,
  19,
  33,
  26,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  32,
  14,
  6,
  37,
  12,
  6,
  19,
  22],
 [2,
  12,
  9,
  21,
  22,
  10,
  27,
  20,
  28,
  26,
  28,
  3,
  17,
  8,
  15,
  19,
  33,
  26,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  18,
  36,
  32,
  37,
  35,
  37,
  35,
  37,
  11,
  13,
  5,
  4,
  35,
  1,
  11,
  32,
  34,
  27,
  29],
 [2,
  12,
  9,
  10,
  27,
  28,
  3,
  17,
  8,
  15,
  19,
  33,
  26,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  18,
  36,
  32,
  37,
  35,
  37,
  35,
  37,
  7,
  16,
  35,
  1,
  23,
  12,
  14,
  29,
  10],
 [2,
  12,
  9,
  21,
  22,
  10

In [50]:
(~(data[:, 1:] == target[:, :-1])).sum()

tensor(0)

In [45]:
data[0][1:]

tensor([12,  9, 10, 27, 28,  3, 17,  8, 15, 19, 33, 26, 34, 18, 36, 32, 37, 30,
        35, 31, 29, 31, 29, 31, 29, 31, 29, 31, 29, 31, 36, 29, 37, 30, 35, 31,
        29, 31, 36, 29, 37, 30, 35, 31, 29, 31, 29, 31, 29, 31, 29, 31, 29, 31,
        36, 29, 37, 35, 37, 13,  5,  4, 11, 35])

In [44]:
target[0]

tensor([12,  9, 10, 27, 28,  3, 17,  8, 15, 19, 33, 26, 34, 18, 36, 32, 37, 30,
        35, 31, 29, 31, 29, 31, 29, 31, 29, 31, 29, 31, 36, 29, 37, 30, 35, 31,
        29, 31, 36, 29, 37, 30, 35, 31, 29, 31, 29, 31, 29, 31, 29, 31, 29, 31,
        36, 29, 37, 35, 37, 13,  5,  4, 11, 35,  1])

In [51]:
# not all of the lengths has been changed

In [11]:
predicted

tensor([22, 18, 20,  8, 33,  8,  4, 38, 37, 32, 19, 18, 17,  2, 28, 25, 29, 29,
        18,  4, 35, 15, 11, 18, 15, 29, 17, 19, 37, 37,  7,  5])

In [14]:
  [ u + [p.item()] for  u, p in  zip(unpadded_data, predicted)]

[[2,
  12,
  9,
  10,
  27,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  26,
  28,
  3,
  17,
  8,
  15,
  19,
  33,
  26,
  34,
  32,
  34,
  17,
  14,
  15,
  19,
  33,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  18,
  36,
  32,
  37,
  30,
  35,
  31,
  29,
  31,
  29,
  31,
  29,
  31,
  29,
  31,
  29,
  31,
  29,
  31,
  29,
  31,
  29,
  31,
  29,
  31,
  29,
  31,
  36,
  29,
  37,
  30,
  35,
  31,
  29,
  31,
  29,
  31,
  36,
  29,
  37,
  35,
  37,
  35,
  37,
  13,
  11,
  4,
  5,
  35,
  22],
 [2,
  12,
  9,
  10,
  27,
  28,
  26,
  28,
  26,
  28,
  3,
  17,
  8,
  15,
  19,
  33,
  26,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  14,
  17,
  15,
  19,
  33,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  32,
  32,
  6,
  14,
  1,
  18],
 [2,
  12,
  9,
  10,
  27,
  28,
  26,
  28,
  3,
  17,
  8,
  15,
  19,
  33,
  26,
  34,
  32,
  34,
  32,
  34,
  32,
  34,
  18,
  36,
  32,


In [16]:
import torch 
a = torch.tensor([1,2,3])

In [17]:
b = a

In [18]:
b

tensor([1, 2, 3])

In [19]:
b[2] = 5

In [20]:
b

tensor([1, 2, 5])

In [21]:
a

tensor([1, 2, 5])