In [1]:
from  Controller import TrainingController_V2

In [2]:
trainer = TrainingController_V2()


| Running on cuda:0  

| Model loaded successfully from: SavedModels/0.6974_Diabetes_BaseNNModel_2021-05-11 17:34:13.220265  


<Figure size 1600x800 with 0 Axes>

In [3]:
trainer.train()


| Training Done! 

| Performing Testing ... 

| Performing Testing ... 

| Evaluation result | Loss [0.6268] | Accuracy [0.6974]  

| Classification Report 
                True     False  accuracy  macro avg  weighted avg
precision   0.705882   0.62500  0.697368   0.665441      0.679276
recall      0.941176   0.20000  0.697368   0.570588      0.697368
f1-score    0.806723   0.30303  0.697368   0.554876      0.641034
support    51.000000  25.00000  0.697368  76.000000     76.000000

| Confusion Matrix 
       True  False
True     48      3
False    20      5


In [4]:
trainer.save_training_result("training_v2.ipynb")


| Model saved successfully to: ./SavedModels/0.6974_Diabetes_BaseNNModel_2021-05-11 18:12:19.137805  


<Figure size 432x288 with 0 Axes>

In [5]:
######## Create a little model to see if it's trainable.

In [6]:
# Check for the accuracy calculation

In [10]:
import torch

In [16]:
input = torch.tensor(trainer.dataset[0][trainer.model.feature_names]).cuda()

In [17]:
norm_input = trainer.model.normalize_input(input)

In [18]:
norm_input

tensor([ 0.6776,  0.8230,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
       device='cuda:0', dtype=torch.float64)

In [19]:
all_premutations = []

In [23]:
input_backup = norm_input.clone()

In [25]:
num_samples = 300

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37


In [ ]:
for i in range(len(trainer.model.feature_names)):
    input_to_permute = input_backup.clone()
    max_range = 1 if trainer.model.mean_ + 0.25 > 1 else trainer.model.mean_ + 0.25  
    min_range = -1 if trainer.model.mean_ - 0.25 < -1 else trainer.model.mean_ - 0.25 
    for p in range(int(round(num_samples/len(trainer.model.feature_names)))):
        
    

In [22]:
1 if False else 0.5

0.5

In [31]:
a = torch.tensor([1.9, 1.3, -1.4, 0.5, 0.7,-0.3])

torch.clip(a, -1, 1)

tensor([ 1.0000,  1.0000, -1.0000,  0.5000,  0.7000, -0.3000])

In [32]:
input_to_permute = input_backup.clone()

In [81]:
max_range = torch.clip(input_to_permute + .5 , - 1, 1)

In [82]:
min_range = torch.clip(input_to_permute - .5, -1, 1)

In [36]:
max_range

tensor([ 0.9276,  1.0000,  0.3936,  1.0000, -0.4360,  0.4523,  0.6659,  1.0000],
       device='cuda:0', dtype=torch.float64)

In [37]:
for i in range(len(trainer.model.feature_names)):

IndentationError: expected an indented block (<ipython-input-37-5c1f248298a1>, line 1)

In [38]:
a = torch.ones(5,5)

In [43]:
a.uniform_(-1, 1)

tensor([[-0.9749,  0.0435,  0.0524,  0.3899,  0.8803],
        [ 0.9429,  0.6522,  0.5863,  0.5084, -0.1987],
        [ 0.3882, -0.5774, -0.9177, -0.5789,  0.4997],
        [-0.5720,  0.9711, -0.8153, -0.1348, -0.4560],
        [-0.5579,  0.7086, -0.3107,  0.5504, -0.5049]])

In [48]:
a[:,1] = 5

In [49]:
a

tensor([[-0.9749,  5.0000,  0.0524,  0.3899,  0.8803],
        [ 5.0000,  5.0000,  5.0000,  5.0000,  5.0000],
        [ 0.3882,  5.0000, -0.9177, -0.5789,  0.4997],
        [-0.5720,  5.0000, -0.8153, -0.1348, -0.4560],
        [-0.5579,  5.0000, -0.3107,  0.5504, -0.5049]])

In [68]:
samples_per_feature =30

In [69]:
ps = input_to_permute.unsqueeze(0).repeat(samples_per_feature, 1)

tensor([ 0.9276,  1.0000,  0.3936,  1.0000, -0.4360,  0.4523,  0.6659,  1.0000],
       device='cuda:0', dtype=torch.float64)

In [70]:
# Using torch concat to concat them

In [83]:
feature_idx_to_permuter = 1

In [84]:
ps[:,feature_idx_to_permuter] = torch.zeros(samples_per_feature).uniform_(min_range[feature_idx_to_permuter], max_range[feature_idx_to_permuter])

In [80]:
ps

tensor([[ 0.6776,  0.8128,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.6374,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.8525,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.8895,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.8288,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.8701,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.8782,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.5981,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.8462,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.6100,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.6193,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776,  0.7290,  0.1436,  0.8830, -0.6860,  0.2023,  0.4159,  1.4825],
        [ 0.6776

In [87]:
ps2  = ps.clone()

In [88]:
ps.size()

torch.Size([30, 8])

In [89]:
ps2.size()

torch.Size([30, 8])

In [91]:
torch.cat([ps, ps2], dim=0).shape

torch.Size([60, 8])